### ISSUE TITLE
Strange inconsistency when unwrapping a string

### ISSUE THREAD

**Issue by mwaterfall** [owensd/json-swift#25]
I'm pulling in some data from the Instagram API and I'm getting something very strange go on when using this json library.

The following code does not fall into the if block, so nextURLString is never unwrapped, as if the value does not exist:

``` swift
if let nextURLString = json["pagination"]["next_url"].string {
    self.nextPaginationURL = NSURL(string: nextURLString) // doesnt exeute
}
```

However a quick check in the console shows that the value does exist at that path:

``` swift
(lldb) po json["pagination"]["next_url"].string!
"https://api.instagram.com/v1/users/..."
```

Strangely, the following code (as an alternative to the `if let` unwrapping) does work, and the code in the if block is executed. 

``` swift
let nextURLString = json["pagination"]["next_url"].string
if nextURLString != nil {
    self.nextPaginationURL = NSURL(string: nextURLString!) // this *is* executed
}
```

Any idea why this could be?

**Comment by owensd** [comment]
Closing as this is super old and seems like a language issue.
