### ISSUE TITLE
Array order different in app than in JSON API

### ISSUE THREAD

**Issue by DaveAlton-CrispMedia** [owensd/json-swift#29]
When I look at the JSON object that this is parsing, the order is not the same as the end parsed data. I have ordered the array in the API, but when I loop through the array in the app, the order is different.

**Comment by JulianMartinez** [comment]
I've been working with this library and I observed the same effect. Data is parsed on different order than provided by API. I don't have more information at the moment. I will try to check it. Apparently no data is lost during parsing process.

**Comment by owensd** [comment]
Super old... but do you have a repro for this?
