### ISSUE TITLE
Pretty printing output is invalid

### ISSUE THREAD

**Issue by potmo** [owensd/json-swift#45]
The line:
https://github.com/owensd/json-swift/blob/master/src/JSValue.swift#L255

The output is
```
{  "key1": "value1"{
,
  "key2": "value2"
}
```
But should be:
```
{
  "key1": "value1",
  "key2": "value2"
}
```

Changing the line to:
`return "{\(newline)" + (dict.map({ "\(nextIndent)\"\($0)\":\(space)\($1.prettyPrint(indent, level + 1))"})).joinWithSeparator(",\(newline)") + "\(newline)\(currentIndent)}"` 
fixes the problem

**Comment by bygri** [comment]
Sorry, that was me who broke it. I've lodged PR #47 using mostly your code in issues #45 and #46. Thank you!
