### ISSUE TITLE
Crash when parsing huge exponents

### ISSUE THREAD

**Issue by nst** [owensd/json-swift#55]
json-swift does crash while parsing file [i_number_huge_exp.json](https://github.com/nst/JSONTestSuite/blob/master/test_parsing/i_number_huge_exp.json) with `fatal error: Double value cannot be converted to Int because the result would be greater than Int.max`

**Comment by owensd** [comment]
I haven't taken a look at any of the i_* files. But good catch. I also need to do more validation with your transform set.

**Comment by nst** [comment]
The results of parsing the i_* files is... undefined, but the lib should return an error instead of crashing.

FYI here is the result of the whole [JSONTestSuite](https://github.com/nst/JSONTestSuite) for json-swift.

<img width="629" alt="screen shot 2017-05-22 at 22 30 43" src="https://cloud.githubusercontent.com/assets/51388/26327632/6c69c966-3f40-11e7-89b7-7ee3d32e5804.png">

**Comment by owensd** [comment]
Oh definitely, it shouldn't crash.
