### ISSUE TITLE
Crash when parsing many open array

### ISSUE THREAD

**Issue by nst** [owensd/json-swift#56]
json-swift does crash while parsing file [n_structure_open_array_object.json](https://github.com/nst/JSONTestSuite/blob/master/test_parsing/n_structure_open_array_object.json) with `EXC_BAD_ACCESS`

**Comment by owensd** [comment]
Interesting... The algorithm is currently a recursive solution. I have a depth guard, I may need to pull that in to workaround the crash.

However, I'll have to change the algorithm to avoid the crash without this depth hack.
