### ISSUE TITLE
Erroneously parsed strings

### ISSUE THREAD

**Issue by nst** [owensd/json-swift#57]
json-swift will parse these strings, even though they are not JSON:

    [-]
    [0.3e+]
    [0.3e]
    [0E+]
    [0E]
    [0e+]
    [0e]
    [1.0e+]
    [1.0e-]
    [1.0e]

**Comment by owensd** [comment]
Hmm... this one is interesting because I have some specific tests for some of these:

    func testParseNumberTwoDot() {
        let string = "[-2.]"
        let jsvalue = try? JSValue.parse(string)
        XCTAssertTrue(jsvalue == nil)
    }

    func testParseNumberTwoDotE3() {
        let string = "[2.e-3]"
        let jsvalue = try? JSValue.parse(string)
        XCTAssertTrue(jsvalue == nil)
    }

This successfully gives me an error. I just added some more tests locally for the rest of the cases and I see an error.

Are you using 2.0.2 and what is your setup?

**Comment by nst** [comment]
My mistake, I messed up with other results.

I just updated the numbers that are parsed but are not part JSON strictly speaking.
